services:

  bank_backend:
    build:
      context: ./backend
    platform: linux/amd64 # for compatibility with arm64
    ports:
      - "8000:8000"
    container_name: bank
    depends_on:
      - bank_db

  bank_db:
    image: postgres:17
    restart: always
    container_name: bank_db
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpassword
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: