CREATE TYPE delivery_status AS ENUM (
    'created',
    'confirmed',
    'cancelled',
    'sent',
    'delivered'
);

CREATE TYPE vehicle_status AS ENUM (
    'available',
    'in_use'
);

CREATE TABLE vehicles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status vehicle_status NOT NULL DEFAULT 'available',
    current_delivery_id INTEGER DEFAULT NULL
);

CREATE TABLE deliveries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INTEGER NOT NULL REFERENCES vehicles (id) ON DELETE NO ACTION ON UPDATE CASCADE,
    status delivery_status NOT NULL DEFAULT 'created',
    cost NUMERIC(12, 2) NOT NULL CHECK (cost > 0),
    time TIMESTAMPTZ NOT NULL,
    local_address TEXT NOT NULL,
    client_address TEXT NOT NULL
);

-- break circular definitions
ALTER TABLE vehicles
    ADD FOREIGN KEY (current_delivery_id) REFERENCES deliveries (id) ON DELETE NO ACTION ON UPDATE CASCADE;

-- insert some vehicles
INSERT INTO vehicles DEFAULT VALUES;
INSERT INTO vehicles DEFAULT VALUES;
INSERT INTO vehicles DEFAULT VALUES;
INSERT INTO vehicles DEFAULT VALUES;
INSERT INTO vehicles DEFAULT VALUES;
