server:
  port: 8080

spring:
  application:
    name: acmeat

  datasource:
    url: ${ACMEAT_DB_URL:jdbc:postgresql://localhost:5432/acmeatdb}
    username: acmeuser
    password: acmepassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # update to "validate" in production
    show-sql: true

camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: ${ZEEBE_GATEWAY_ADDRESS:http://localhost:26500}

rest:
  restaurant:
    base-urls:
      1: ${RESTAURANT1_BASE_URL:http://localhost:9001}
      2: ${RESTAURANT2_BASE_URL:http://localhost:9002}
  gis:
    base-url: ${GIS_BASE_URL:http://localhost:6002}
  shipping-company:
    base-urls:
      1: ${SHIPPING_SERVICE1_BASE_URL:http://localhost:5001}
      2: ${SHIPPING_SERVICE2_BASE_URL:http://localhost:5005}

soap:
  bank:
    endpoint: ${BANK_BASE_URL:http://localhost:8000}
