-- Enum of payment status
CREATE TYPE payment_status AS ENUM (
    'created',      -- payment created and money debited, but not yet validated
    'validated',    -- token verified, payment awaiting final confirmation
    'completed',    -- order delivered, payment credited to recipient
    'refunded',     -- order cancelled, money returned to the payer
    'error'         -- NOT USED - payment failed, money not debited
);

-- Accounts table
CREATE TABLE accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    balance NUMERIC(12, 2) NOT NULL CHECK (balance >= 0)
);

-- Payments table
-- Note: we do not store the payee (recipient) account because it is always ACME
CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payer_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE SET NULL ON UPDATE CASCADE,
    order_id INTEGER NOT NULL,
    token TEXT NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    status payment_status NOT NULL DEFAULT 'created',
    UNIQUE (order_id)
);

-- Demo data
INSERT INTO accounts (username, password, balance) 
VALUES
    ('acme', 'acme', 0.00),
    ('demo', 'demo', 200.00);