-- Enum of payment status
CREATE TYPE payment_status AS ENUM (
    'created',      -- payment created and awaiting payment
    'paid',         -- payment completed, money debited from payer
    'validated',    -- token verified, payment awaiting final confirmation
    'completed',    -- order delivered, payment credited to recipient
    'refunded'      -- order cancelled, money returned to the payer
);

-- Accounts table
CREATE TABLE accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    balance NUMERIC(12, 2) NOT NULL CHECK (balance >= 0)
);

-- Payments table
CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE SET NULL ON UPDATE CASCADE,
    payer_id INTEGER REFERENCES accounts(id) ON DELETE SET NULL ON UPDATE CASCADE,
    order_id INTEGER NOT NULL,
    token TEXT UNIQUE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    status payment_status NOT NULL DEFAULT 'created',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP,
    validated_at TIMESTAMP,
    confirmed_at TIMESTAMP
);

-- Demo data
INSERT INTO accounts (username, password, balance) 
VALUES
    ('acme', 'acme', 0.00),
    ('demo', 'demo', 200.00);